name: docker-tests-java-client

services:

  marklogic:
    image: "${MARKLOGIC_IMAGE}"
    platform: linux/arm64
    environment:
      - INSTALL_CONVERTERS=false
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
      - MARKLOGIC_WALLET_PASSWORD=admin
    # The NET_RAW capability allows a process to create raw sockets. Polaris does not like that.
    # This setting removes the NET_RAW capability from the container.
    cap_drop:
      - NET_RAW
    volumes:
      - ${MARKLOGIC_LOGS_VOLUME}:/var/opt/MarkLogic/Logs
    ports:
      - "8000-8002:8000-8002"
      - "8010-8015:8010-8015" # Range of ports used by app servers, at least one of which - 8015 - is created by a test.

volumes:
  marklogicLogs:
