/*
 * Copyright 2016-2017 MarkLogic Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.marklogic.client.expression;

import com.marklogic.client.type.MapMapExpr;
import com.marklogic.client.type.XsAnyAtomicTypeExpr;
import com.marklogic.client.type.XsAnyAtomicTypeSeqExpr;
import com.marklogic.client.type.XsDateTimeExpr;
import com.marklogic.client.type.XsDoubleExpr;
import com.marklogic.client.type.XsQNameExpr;
import com.marklogic.client.type.XsQNameSeqExpr;
import com.marklogic.client.type.XsStringExpr;
import com.marklogic.client.type.XsStringSeqExpr;

import com.marklogic.client.type.CtsBoxExpr;
import com.marklogic.client.type.CtsBoxSeqExpr;
import com.marklogic.client.type.CtsCircleExpr;
import com.marklogic.client.type.CtsCircleSeqExpr;
import com.marklogic.client.type.CtsPeriodExpr;
import com.marklogic.client.type.CtsPeriodSeqExpr;
import com.marklogic.client.type.CtsPointExpr;
import com.marklogic.client.type.CtsPointSeqExpr;
import com.marklogic.client.type.CtsPolygonExpr;
import com.marklogic.client.type.CtsPolygonSeqExpr;
import com.marklogic.client.type.CtsQueryExpr;
import com.marklogic.client.type.CtsQuerySeqExpr;
import com.marklogic.client.type.CtsReferenceExpr;
import com.marklogic.client.type.CtsReferenceSeqExpr;
import com.marklogic.client.type.CtsRegionExpr;
import com.marklogic.client.type.CtsRegionSeqExpr;

// IMPORTANT: Do not edit. This file is generated. 
public interface CtsExpr {
    public CtsQueryExpr andNotQuery(CtsQueryExpr positiveQuery, CtsQueryExpr negativeQuery);
    public CtsQueryExpr andQuery(CtsQueryExpr... queries);
    public CtsQueryExpr andQuery(CtsQuerySeqExpr queries);
    public CtsQueryExpr andQuery(CtsQuerySeqExpr queries, String options);
    public CtsQueryExpr andQuery(CtsQuerySeqExpr queries, XsStringSeqExpr options);
    public CtsQueryExpr boostQuery(CtsQueryExpr matchingQuery, CtsQueryExpr boostingQuery);
    public CtsBoxExpr box(XsDoubleExpr south, double west, double north, double east);
    public CtsBoxExpr box(XsDoubleExpr south, XsDoubleExpr west, XsDoubleExpr north, XsDoubleExpr east);
    public CtsCircleExpr circle(XsDoubleExpr radius, CtsPointExpr center);
    public CtsQueryExpr collectionQuery(String uris);
    public CtsQueryExpr collectionQuery(XsStringSeqExpr uris);
    public CtsReferenceExpr collectionReference();
    public CtsReferenceExpr collectionReference(String options);
    public CtsReferenceExpr collectionReference(XsStringSeqExpr options);
    public CtsQueryExpr directoryQuery(String uris);
    public CtsQueryExpr directoryQuery(XsStringSeqExpr uris);
    public CtsQueryExpr directoryQuery(String uris, String depth);
    public CtsQueryExpr directoryQuery(XsStringSeqExpr uris, XsStringExpr depth);
    public CtsQueryExpr documentFragmentQuery(CtsQueryExpr query);
    public CtsQueryExpr documentQuery(String uris);
    public CtsQueryExpr documentQuery(XsStringSeqExpr uris);
    public CtsQueryExpr elementAttributePairGeospatialQuery(String elementName, String latitudeAttributeNames, String longitudeAttributeNames, CtsRegionExpr... regions);
    public CtsQueryExpr elementAttributePairGeospatialQuery(XsQNameSeqExpr elementName, XsQNameSeqExpr latitudeAttributeNames, XsQNameSeqExpr longitudeAttributeNames, CtsRegionSeqExpr regions);
    public CtsQueryExpr elementAttributePairGeospatialQuery(String elementName, String latitudeAttributeNames, String longitudeAttributeNames, CtsRegionSeqExpr regions, String... options);
    public CtsQueryExpr elementAttributePairGeospatialQuery(XsQNameSeqExpr elementName, XsQNameSeqExpr latitudeAttributeNames, XsQNameSeqExpr longitudeAttributeNames, CtsRegionSeqExpr regions, XsStringSeqExpr options);
    public CtsQueryExpr elementAttributePairGeospatialQuery(String elementName, String latitudeAttributeNames, String longitudeAttributeNames, CtsRegionSeqExpr regions, String options, double weight);
    public CtsQueryExpr elementAttributePairGeospatialQuery(XsQNameSeqExpr elementName, XsQNameSeqExpr latitudeAttributeNames, XsQNameSeqExpr longitudeAttributeNames, CtsRegionSeqExpr regions, XsStringSeqExpr options, XsDoubleExpr weight);
    public CtsQueryExpr elementAttributeRangeQuery(String elementName, String attributeName, String operator, String value);
    public CtsQueryExpr elementAttributeRangeQuery(XsQNameSeqExpr elementName, XsQNameSeqExpr attributeName, XsStringExpr operator, XsAnyAtomicTypeSeqExpr value);
    public CtsQueryExpr elementAttributeRangeQuery(String elementName, String attributeName, String operator, String value, String... options);
    public CtsQueryExpr elementAttributeRangeQuery(XsQNameSeqExpr elementName, XsQNameSeqExpr attributeName, XsStringExpr operator, XsAnyAtomicTypeSeqExpr value, XsStringSeqExpr options);
    public CtsQueryExpr elementAttributeRangeQuery(String elementName, String attributeName, String operator, String value, String options, double weight);
    public CtsQueryExpr elementAttributeRangeQuery(XsQNameSeqExpr elementName, XsQNameSeqExpr attributeName, XsStringExpr operator, XsAnyAtomicTypeSeqExpr value, XsStringSeqExpr options, XsDoubleExpr weight);
    public CtsReferenceExpr elementAttributeReference(String element, String attribute);
    public CtsReferenceExpr elementAttributeReference(XsQNameExpr element, XsQNameExpr attribute);
    public CtsReferenceExpr elementAttributeReference(String element, String attribute, String options);
    public CtsReferenceExpr elementAttributeReference(XsQNameExpr element, XsQNameExpr attribute, XsStringSeqExpr options);
    public CtsQueryExpr elementAttributeValueQuery(String elementName, String attributeName, String text);
    public CtsQueryExpr elementAttributeValueQuery(XsQNameSeqExpr elementName, XsQNameSeqExpr attributeName, XsStringSeqExpr text);
    public CtsQueryExpr elementAttributeValueQuery(String elementName, String attributeName, String text, String... options);
    public CtsQueryExpr elementAttributeValueQuery(XsQNameSeqExpr elementName, XsQNameSeqExpr attributeName, XsStringSeqExpr text, XsStringSeqExpr options);
    public CtsQueryExpr elementAttributeValueQuery(String elementName, String attributeName, String text, String options, double weight);
    public CtsQueryExpr elementAttributeValueQuery(XsQNameSeqExpr elementName, XsQNameSeqExpr attributeName, XsStringSeqExpr text, XsStringSeqExpr options, XsDoubleExpr weight);
    public CtsQueryExpr elementAttributeWordQuery(String elementName, String attributeName, String text);
    public CtsQueryExpr elementAttributeWordQuery(XsQNameSeqExpr elementName, XsQNameSeqExpr attributeName, XsStringSeqExpr text);
    public CtsQueryExpr elementAttributeWordQuery(String elementName, String attributeName, String text, String... options);
    public CtsQueryExpr elementAttributeWordQuery(XsQNameSeqExpr elementName, XsQNameSeqExpr attributeName, XsStringSeqExpr text, XsStringSeqExpr options);
    public CtsQueryExpr elementAttributeWordQuery(String elementName, String attributeName, String text, String options, double weight);
    public CtsQueryExpr elementAttributeWordQuery(XsQNameSeqExpr elementName, XsQNameSeqExpr attributeName, XsStringSeqExpr text, XsStringSeqExpr options, XsDoubleExpr weight);
    public CtsQueryExpr elementChildGeospatialQuery(String parentElementName, String childElementNames, CtsRegionExpr... regions);
    public CtsQueryExpr elementChildGeospatialQuery(XsQNameSeqExpr parentElementName, XsQNameSeqExpr childElementNames, CtsRegionSeqExpr regions);
    public CtsQueryExpr elementChildGeospatialQuery(String parentElementName, String childElementNames, CtsRegionSeqExpr regions, String... options);
    public CtsQueryExpr elementChildGeospatialQuery(XsQNameSeqExpr parentElementName, XsQNameSeqExpr childElementNames, CtsRegionSeqExpr regions, XsStringSeqExpr options);
    public CtsQueryExpr elementChildGeospatialQuery(String parentElementName, String childElementNames, CtsRegionSeqExpr regions, String options, double weight);
    public CtsQueryExpr elementChildGeospatialQuery(XsQNameSeqExpr parentElementName, XsQNameSeqExpr childElementNames, CtsRegionSeqExpr regions, XsStringSeqExpr options, XsDoubleExpr weight);
    public CtsQueryExpr elementGeospatialQuery(String elementName, CtsRegionExpr... regions);
    public CtsQueryExpr elementGeospatialQuery(XsQNameSeqExpr elementName, CtsRegionSeqExpr regions);
    public CtsQueryExpr elementGeospatialQuery(String elementName, CtsRegionSeqExpr regions, String... options);
    public CtsQueryExpr elementGeospatialQuery(XsQNameSeqExpr elementName, CtsRegionSeqExpr regions, XsStringSeqExpr options);
    public CtsQueryExpr elementGeospatialQuery(String elementName, CtsRegionSeqExpr regions, String options, double weight);
    public CtsQueryExpr elementGeospatialQuery(XsQNameSeqExpr elementName, CtsRegionSeqExpr regions, XsStringSeqExpr options, XsDoubleExpr weight);
    public CtsQueryExpr elementPairGeospatialQuery(String elementName, String latitudeElementNames, String longitudeElementNames, CtsRegionExpr... regions);
    public CtsQueryExpr elementPairGeospatialQuery(XsQNameSeqExpr elementName, XsQNameSeqExpr latitudeElementNames, XsQNameSeqExpr longitudeElementNames, CtsRegionSeqExpr regions);
    public CtsQueryExpr elementPairGeospatialQuery(String elementName, String latitudeElementNames, String longitudeElementNames, CtsRegionSeqExpr regions, String... options);
    public CtsQueryExpr elementPairGeospatialQuery(XsQNameSeqExpr elementName, XsQNameSeqExpr latitudeElementNames, XsQNameSeqExpr longitudeElementNames, CtsRegionSeqExpr regions, XsStringSeqExpr options);
    public CtsQueryExpr elementPairGeospatialQuery(String elementName, String latitudeElementNames, String longitudeElementNames, CtsRegionSeqExpr regions, String options, double weight);
    public CtsQueryExpr elementPairGeospatialQuery(XsQNameSeqExpr elementName, XsQNameSeqExpr latitudeElementNames, XsQNameSeqExpr longitudeElementNames, CtsRegionSeqExpr regions, XsStringSeqExpr options, XsDoubleExpr weight);
    public CtsQueryExpr elementQuery(String elementName, CtsQueryExpr query);
    public CtsQueryExpr elementQuery(XsQNameSeqExpr elementName, CtsQueryExpr query);
    public CtsQueryExpr elementRangeQuery(String elementName, String operator, String value);
    public CtsQueryExpr elementRangeQuery(XsQNameSeqExpr elementName, XsStringExpr operator, XsAnyAtomicTypeSeqExpr value);
    public CtsQueryExpr elementRangeQuery(String elementName, String operator, String value, String... options);
    public CtsQueryExpr elementRangeQuery(XsQNameSeqExpr elementName, XsStringExpr operator, XsAnyAtomicTypeSeqExpr value, XsStringSeqExpr options);
    public CtsQueryExpr elementRangeQuery(String elementName, String operator, String value, String options, double weight);
    public CtsQueryExpr elementRangeQuery(XsQNameSeqExpr elementName, XsStringExpr operator, XsAnyAtomicTypeSeqExpr value, XsStringSeqExpr options, XsDoubleExpr weight);
    public CtsReferenceExpr elementReference(String element);
    public CtsReferenceExpr elementReference(XsQNameExpr element);
    public CtsReferenceExpr elementReference(String element, String options);
    public CtsReferenceExpr elementReference(XsQNameExpr element, XsStringSeqExpr options);
    public CtsQueryExpr elementValueQuery(String elementName);
    public CtsQueryExpr elementValueQuery(XsQNameSeqExpr elementName);
    public CtsQueryExpr elementValueQuery(String elementName, String text);
    public CtsQueryExpr elementValueQuery(XsQNameSeqExpr elementName, XsStringSeqExpr text);
    public CtsQueryExpr elementValueQuery(String elementName, String text, String... options);
    public CtsQueryExpr elementValueQuery(XsQNameSeqExpr elementName, XsStringSeqExpr text, XsStringSeqExpr options);
    public CtsQueryExpr elementValueQuery(String elementName, String text, String options, double weight);
    public CtsQueryExpr elementValueQuery(XsQNameSeqExpr elementName, XsStringSeqExpr text, XsStringSeqExpr options, XsDoubleExpr weight);
    public CtsQueryExpr elementWordQuery(String elementName, String text);
    public CtsQueryExpr elementWordQuery(XsQNameSeqExpr elementName, XsStringSeqExpr text);
    public CtsQueryExpr elementWordQuery(String elementName, String text, String... options);
    public CtsQueryExpr elementWordQuery(XsQNameSeqExpr elementName, XsStringSeqExpr text, XsStringSeqExpr options);
    public CtsQueryExpr elementWordQuery(String elementName, String text, String options, double weight);
    public CtsQueryExpr elementWordQuery(XsQNameSeqExpr elementName, XsStringSeqExpr text, XsStringSeqExpr options, XsDoubleExpr weight);
    public CtsQueryExpr falseQuery();
    public CtsQueryExpr fieldRangeQuery(String fieldName, String operator, String value);
    public CtsQueryExpr fieldRangeQuery(XsStringSeqExpr fieldName, XsStringExpr operator, XsAnyAtomicTypeSeqExpr value);
    public CtsQueryExpr fieldRangeQuery(String fieldName, String operator, String value, String... options);
    public CtsQueryExpr fieldRangeQuery(XsStringSeqExpr fieldName, XsStringExpr operator, XsAnyAtomicTypeSeqExpr value, XsStringSeqExpr options);
    public CtsQueryExpr fieldRangeQuery(String fieldName, String operator, String value, String options, double weight);
    public CtsQueryExpr fieldRangeQuery(XsStringSeqExpr fieldName, XsStringExpr operator, XsAnyAtomicTypeSeqExpr value, XsStringSeqExpr options, XsDoubleExpr weight);
    public CtsReferenceExpr fieldReference(String field);
    public CtsReferenceExpr fieldReference(XsStringExpr field);
    public CtsReferenceExpr fieldReference(String field, String options);
    public CtsReferenceExpr fieldReference(XsStringExpr field, XsStringSeqExpr options);
    public CtsQueryExpr fieldValueQuery(String fieldName, String text);
    public CtsQueryExpr fieldValueQuery(XsStringSeqExpr fieldName, XsAnyAtomicTypeSeqExpr text);
    public CtsQueryExpr fieldValueQuery(String fieldName, String text, String... options);
    public CtsQueryExpr fieldValueQuery(XsStringSeqExpr fieldName, XsAnyAtomicTypeSeqExpr text, XsStringSeqExpr options);
    public CtsQueryExpr fieldValueQuery(String fieldName, String text, String options, double weight);
    public CtsQueryExpr fieldValueQuery(XsStringSeqExpr fieldName, XsAnyAtomicTypeSeqExpr text, XsStringSeqExpr options, XsDoubleExpr weight);
    public CtsQueryExpr fieldWordQuery(String fieldName, String text);
    public CtsQueryExpr fieldWordQuery(XsStringSeqExpr fieldName, XsStringSeqExpr text);
    public CtsQueryExpr fieldWordQuery(String fieldName, String text, String... options);
    public CtsQueryExpr fieldWordQuery(XsStringSeqExpr fieldName, XsStringSeqExpr text, XsStringSeqExpr options);
    public CtsQueryExpr fieldWordQuery(String fieldName, String text, String options, double weight);
    public CtsQueryExpr fieldWordQuery(XsStringSeqExpr fieldName, XsStringSeqExpr text, XsStringSeqExpr options, XsDoubleExpr weight);
    public CtsQueryExpr jsonPropertyChildGeospatialQuery(String parentPropertyName, String childPropertyNames, CtsRegionExpr... regions);
    public CtsQueryExpr jsonPropertyChildGeospatialQuery(XsStringSeqExpr parentPropertyName, XsStringSeqExpr childPropertyNames, CtsRegionSeqExpr regions);
    public CtsQueryExpr jsonPropertyChildGeospatialQuery(String parentPropertyName, String childPropertyNames, CtsRegionSeqExpr regions, String... options);
    public CtsQueryExpr jsonPropertyChildGeospatialQuery(XsStringSeqExpr parentPropertyName, XsStringSeqExpr childPropertyNames, CtsRegionSeqExpr regions, XsStringSeqExpr options);
    public CtsQueryExpr jsonPropertyChildGeospatialQuery(String parentPropertyName, String childPropertyNames, CtsRegionSeqExpr regions, String options, double weight);
    public CtsQueryExpr jsonPropertyChildGeospatialQuery(XsStringSeqExpr parentPropertyName, XsStringSeqExpr childPropertyNames, CtsRegionSeqExpr regions, XsStringSeqExpr options, XsDoubleExpr weight);
    public CtsQueryExpr jsonPropertyGeospatialQuery(String propertyName, CtsRegionExpr... regions);
    public CtsQueryExpr jsonPropertyGeospatialQuery(XsStringSeqExpr propertyName, CtsRegionSeqExpr regions);
    public CtsQueryExpr jsonPropertyGeospatialQuery(String propertyName, CtsRegionSeqExpr regions, String... options);
    public CtsQueryExpr jsonPropertyGeospatialQuery(XsStringSeqExpr propertyName, CtsRegionSeqExpr regions, XsStringSeqExpr options);
    public CtsQueryExpr jsonPropertyGeospatialQuery(String propertyName, CtsRegionSeqExpr regions, String options, double weight);
    public CtsQueryExpr jsonPropertyGeospatialQuery(XsStringSeqExpr propertyName, CtsRegionSeqExpr regions, XsStringSeqExpr options, XsDoubleExpr weight);
    public CtsQueryExpr jsonPropertyPairGeospatialQuery(String propertyName, String latitudePropertyNames, String longitudePropertyNames, CtsRegionExpr... regions);
    public CtsQueryExpr jsonPropertyPairGeospatialQuery(XsStringSeqExpr propertyName, XsStringSeqExpr latitudePropertyNames, XsStringSeqExpr longitudePropertyNames, CtsRegionSeqExpr regions);
    public CtsQueryExpr jsonPropertyPairGeospatialQuery(String propertyName, String latitudePropertyNames, String longitudePropertyNames, CtsRegionSeqExpr regions, String... options);
    public CtsQueryExpr jsonPropertyPairGeospatialQuery(XsStringSeqExpr propertyName, XsStringSeqExpr latitudePropertyNames, XsStringSeqExpr longitudePropertyNames, CtsRegionSeqExpr regions, XsStringSeqExpr options);
    public CtsQueryExpr jsonPropertyPairGeospatialQuery(String propertyName, String latitudePropertyNames, String longitudePropertyNames, CtsRegionSeqExpr regions, String options, double weight);
    public CtsQueryExpr jsonPropertyPairGeospatialQuery(XsStringSeqExpr propertyName, XsStringSeqExpr latitudePropertyNames, XsStringSeqExpr longitudePropertyNames, CtsRegionSeqExpr regions, XsStringSeqExpr options, XsDoubleExpr weight);
    public CtsQueryExpr jsonPropertyRangeQuery(String propertyName, String operator, String value);
    public CtsQueryExpr jsonPropertyRangeQuery(XsStringSeqExpr propertyName, XsStringExpr operator, XsAnyAtomicTypeSeqExpr value);
    public CtsQueryExpr jsonPropertyRangeQuery(String propertyName, String operator, String value, String... options);
    public CtsQueryExpr jsonPropertyRangeQuery(XsStringSeqExpr propertyName, XsStringExpr operator, XsAnyAtomicTypeSeqExpr value, XsStringSeqExpr options);
    public CtsQueryExpr jsonPropertyRangeQuery(String propertyName, String operator, String value, String options, double weight);
    public CtsQueryExpr jsonPropertyRangeQuery(XsStringSeqExpr propertyName, XsStringExpr operator, XsAnyAtomicTypeSeqExpr value, XsStringSeqExpr options, XsDoubleExpr weight);
    public CtsReferenceExpr jsonPropertyReference(String property);
    public CtsReferenceExpr jsonPropertyReference(XsStringExpr property);
    public CtsReferenceExpr jsonPropertyReference(String property, String options);
    public CtsReferenceExpr jsonPropertyReference(XsStringExpr property, XsStringSeqExpr options);
    public CtsQueryExpr jsonPropertyScopeQuery(String propertyName, CtsQueryExpr query);
    public CtsQueryExpr jsonPropertyScopeQuery(XsStringSeqExpr propertyName, CtsQueryExpr query);
    public CtsQueryExpr jsonPropertyValueQuery(String propertyName, String value);
    public CtsQueryExpr jsonPropertyValueQuery(XsStringSeqExpr propertyName, XsAnyAtomicTypeSeqExpr value);
    public CtsQueryExpr jsonPropertyValueQuery(String propertyName, String value, String... options);
    public CtsQueryExpr jsonPropertyValueQuery(XsStringSeqExpr propertyName, XsAnyAtomicTypeSeqExpr value, XsStringSeqExpr options);
    public CtsQueryExpr jsonPropertyValueQuery(String propertyName, String value, String options, double weight);
    public CtsQueryExpr jsonPropertyValueQuery(XsStringSeqExpr propertyName, XsAnyAtomicTypeSeqExpr value, XsStringSeqExpr options, XsDoubleExpr weight);
    public CtsQueryExpr jsonPropertyWordQuery(String propertyName, String text);
    public CtsQueryExpr jsonPropertyWordQuery(XsStringSeqExpr propertyName, XsStringSeqExpr text);
    public CtsQueryExpr jsonPropertyWordQuery(String propertyName, String text, String... options);
    public CtsQueryExpr jsonPropertyWordQuery(XsStringSeqExpr propertyName, XsStringSeqExpr text, XsStringSeqExpr options);
    public CtsQueryExpr jsonPropertyWordQuery(String propertyName, String text, String options, double weight);
    public CtsQueryExpr jsonPropertyWordQuery(XsStringSeqExpr propertyName, XsStringSeqExpr text, XsStringSeqExpr options, XsDoubleExpr weight);
    public CtsQueryExpr locksFragmentQuery(CtsQueryExpr query);
    public CtsQueryExpr lsqtQuery(String temporalCollection);
    public CtsQueryExpr lsqtQuery(XsStringExpr temporalCollection);
    public CtsQueryExpr lsqtQuery(String temporalCollection, String timestamp);
    public CtsQueryExpr lsqtQuery(XsStringExpr temporalCollection, XsDateTimeExpr timestamp);
    public CtsQueryExpr lsqtQuery(String temporalCollection, String timestamp, String... options);
    public CtsQueryExpr lsqtQuery(XsStringExpr temporalCollection, XsDateTimeExpr timestamp, XsStringSeqExpr options);
    public CtsQueryExpr lsqtQuery(String temporalCollection, String timestamp, String options, double weight);
    public CtsQueryExpr lsqtQuery(XsStringExpr temporalCollection, XsDateTimeExpr timestamp, XsStringSeqExpr options, XsDoubleExpr weight);
    public CtsQueryExpr nearQuery(CtsQueryExpr... queries);
    public CtsQueryExpr nearQuery(CtsQuerySeqExpr queries);
    public CtsQueryExpr nearQuery(CtsQuerySeqExpr queries, double distance);
    public CtsQueryExpr nearQuery(CtsQuerySeqExpr queries, XsDoubleExpr distance);
    public CtsQueryExpr nearQuery(CtsQuerySeqExpr queries, double distance, String... options);
    public CtsQueryExpr nearQuery(CtsQuerySeqExpr queries, XsDoubleExpr distance, XsStringSeqExpr options);
    public CtsQueryExpr nearQuery(CtsQuerySeqExpr queries, double distance, String options, double distanceWeight);
    public CtsQueryExpr nearQuery(CtsQuerySeqExpr queries, XsDoubleExpr distance, XsStringSeqExpr options, XsDoubleExpr distanceWeight);
    public CtsQueryExpr notInQuery(CtsQueryExpr positiveQuery, CtsQueryExpr negativeQuery);
    public CtsQueryExpr notQuery(CtsQueryExpr query);
    public CtsQueryExpr orQuery(CtsQueryExpr... queries);
    public CtsQueryExpr orQuery(CtsQuerySeqExpr queries);
    public CtsQueryExpr orQuery(CtsQuerySeqExpr queries, String options);
    public CtsQueryExpr orQuery(CtsQuerySeqExpr queries, XsStringSeqExpr options);
    public CtsQueryExpr pathGeospatialQuery(String pathExpression, CtsRegionExpr... regions);
    public CtsQueryExpr pathGeospatialQuery(XsStringSeqExpr pathExpression, CtsRegionSeqExpr regions);
    public CtsQueryExpr pathGeospatialQuery(String pathExpression, CtsRegionSeqExpr regions, String... options);
    public CtsQueryExpr pathGeospatialQuery(XsStringSeqExpr pathExpression, CtsRegionSeqExpr regions, XsStringSeqExpr options);
    public CtsQueryExpr pathGeospatialQuery(String pathExpression, CtsRegionSeqExpr regions, String options, double weight);
    public CtsQueryExpr pathGeospatialQuery(XsStringSeqExpr pathExpression, CtsRegionSeqExpr regions, XsStringSeqExpr options, XsDoubleExpr weight);
    public CtsQueryExpr pathRangeQuery(String pathExpression, String operator, String value);
    public CtsQueryExpr pathRangeQuery(XsStringSeqExpr pathExpression, XsStringExpr operator, XsAnyAtomicTypeSeqExpr value);
    public CtsQueryExpr pathRangeQuery(String pathExpression, String operator, String value, String... options);
    public CtsQueryExpr pathRangeQuery(XsStringSeqExpr pathExpression, XsStringExpr operator, XsAnyAtomicTypeSeqExpr value, XsStringSeqExpr options);
    public CtsQueryExpr pathRangeQuery(String pathExpression, String operator, String value, String options, double weight);
    public CtsQueryExpr pathRangeQuery(XsStringSeqExpr pathExpression, XsStringExpr operator, XsAnyAtomicTypeSeqExpr value, XsStringSeqExpr options, XsDoubleExpr weight);
    public CtsReferenceExpr pathReference(String pathExpression);
    public CtsReferenceExpr pathReference(XsStringExpr pathExpression);
    public CtsReferenceExpr pathReference(String pathExpression, String options);
    public CtsReferenceExpr pathReference(XsStringExpr pathExpression, XsStringSeqExpr options);
    public CtsReferenceExpr pathReference(String pathExpression, String options, MapMapExpr map);
    public CtsReferenceExpr pathReference(XsStringExpr pathExpression, XsStringSeqExpr options, MapMapExpr map);
    public CtsPeriodExpr period(String start, String end);
    public CtsPeriodExpr period(XsDateTimeExpr start, XsDateTimeExpr end);
    public CtsQueryExpr periodCompareQuery(String axis1, String operator, String axis2);
    public CtsQueryExpr periodCompareQuery(XsStringExpr axis1, XsStringExpr operator, XsStringExpr axis2);
    public CtsQueryExpr periodCompareQuery(String axis1, String operator, String axis2, String options);
    public CtsQueryExpr periodCompareQuery(XsStringExpr axis1, XsStringExpr operator, XsStringExpr axis2, XsStringSeqExpr options);
    public CtsQueryExpr periodRangeQuery(String axisName, String operator);
    public CtsQueryExpr periodRangeQuery(XsStringSeqExpr axisName, XsStringExpr operator);
    public CtsQueryExpr periodRangeQuery(String axisName, String operator, CtsPeriodExpr... period);
    public CtsQueryExpr periodRangeQuery(XsStringSeqExpr axisName, XsStringExpr operator, CtsPeriodSeqExpr period);
    public CtsQueryExpr periodRangeQuery(String axisName, String operator, CtsPeriodSeqExpr period, String options);
    public CtsQueryExpr periodRangeQuery(XsStringSeqExpr axisName, XsStringExpr operator, CtsPeriodSeqExpr period, XsStringSeqExpr options);
    public CtsPointExpr point(XsDoubleExpr latitude, double longitude);
    public CtsPointExpr point(XsDoubleExpr latitude, XsDoubleExpr longitude);
    public CtsPolygonExpr polygon(XsAnyAtomicTypeSeqExpr vertices);
    public CtsQueryExpr propertiesFragmentQuery(CtsQueryExpr query);
    public XsStringSeqExpr stem(XsStringExpr text);
    public XsStringSeqExpr stem(XsStringExpr text, String language);
    public XsStringSeqExpr stem(XsStringExpr text, XsStringExpr language);
    public XsStringSeqExpr tokenize(XsStringExpr text);
    public XsStringSeqExpr tokenize(XsStringExpr text, String language);
    public XsStringSeqExpr tokenize(XsStringExpr text, XsStringExpr language);
    public XsStringSeqExpr tokenize(XsStringExpr text, String language, String field);
    public XsStringSeqExpr tokenize(XsStringExpr text, XsStringExpr language, XsStringExpr field);
    public CtsQueryExpr tripleRangeQuery(String subject, String predicate, String object);
    public CtsQueryExpr tripleRangeQuery(XsAnyAtomicTypeSeqExpr subject, XsAnyAtomicTypeSeqExpr predicate, XsAnyAtomicTypeSeqExpr object);
    public CtsQueryExpr tripleRangeQuery(String subject, String predicate, String object, String operator);
    public CtsQueryExpr tripleRangeQuery(XsAnyAtomicTypeSeqExpr subject, XsAnyAtomicTypeSeqExpr predicate, XsAnyAtomicTypeSeqExpr object, XsStringSeqExpr operator);
    public CtsQueryExpr tripleRangeQuery(String subject, String predicate, String object, String operator, String... options);
    public CtsQueryExpr tripleRangeQuery(XsAnyAtomicTypeSeqExpr subject, XsAnyAtomicTypeSeqExpr predicate, XsAnyAtomicTypeSeqExpr object, XsStringSeqExpr operator, XsStringSeqExpr options);
    public CtsQueryExpr tripleRangeQuery(String subject, String predicate, String object, String operator, String options, double weight);
    public CtsQueryExpr tripleRangeQuery(XsAnyAtomicTypeSeqExpr subject, XsAnyAtomicTypeSeqExpr predicate, XsAnyAtomicTypeSeqExpr object, XsStringSeqExpr operator, XsStringSeqExpr options, XsDoubleExpr weight);
    public CtsQueryExpr trueQuery();
    public CtsReferenceExpr uriReference();
    public CtsQueryExpr wordQuery(String text);
    public CtsQueryExpr wordQuery(XsStringSeqExpr text);
    public CtsQueryExpr wordQuery(String text, String... options);
    public CtsQueryExpr wordQuery(XsStringSeqExpr text, XsStringSeqExpr options);
    public CtsQueryExpr wordQuery(String text, String options, double weight);
    public CtsQueryExpr wordQuery(XsStringSeqExpr text, XsStringSeqExpr options, XsDoubleExpr weight);
    public CtsBoxSeqExpr boxSeq(CtsBoxExpr... items);
 
    public CtsCircleSeqExpr circleSeq(CtsCircleExpr... items);
 
    public CtsPeriodSeqExpr periodSeq(CtsPeriodExpr... items);
 
    public CtsPointSeqExpr pointSeq(CtsPointExpr... items);
 
    public CtsPolygonSeqExpr polygonSeq(CtsPolygonExpr... items);
 
    public CtsQuerySeqExpr querySeq(CtsQueryExpr... items);
 
    public CtsReferenceSeqExpr referenceSeq(CtsReferenceExpr... items);
 
    public CtsRegionSeqExpr regionSeq(CtsRegionExpr... items);

}
