*=test-data
suggestion.xml=http://some.org/suggestions,test-data
first.xml=http://some.org/collection1,http://some.org/collection2,test-data
lexicon-test1.xml=http://some.org/collection1,http://some.org/collection2,test-data
lexicon-test2.xml=http://some.org/collection1,http://some.org/collection2,test-data
second.txt=document-format-query-test,test-data
