//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.20 at 02:46:45 PM PDT 
//


package com.marklogic.client.config.search.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;

public class AdditionalQuery
    extends JAXBElement<AnyCtsElement>
{

    protected final static QName NAME = new QName("http://marklogic.com/appservices/search", "additional-query");

    public AdditionalQuery(AnyCtsElement value) {
        super(NAME, ((Class) AnyCtsElement.class), null, value);
    }

    public AdditionalQuery() {
        super(NAME, ((Class) AnyCtsElement.class), null, null);
    }

}
