//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.20 at 02:46:45 PM PDT 
//


package com.marklogic.client.config.search.jaxb;

import java.util.List;
import java.util.Vector;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;choice>
 *           &lt;element ref="{http://marklogic.com/appservices/search}constraint-type"/>
 *           &lt;element ref="{http://marklogic.com/appservices/search}word-lexicon"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://marklogic.com/appservices/search}suggestion-option"/>
 *         &lt;element ref="{http://marklogic.com/appservices/search}annotation"/>
 *       &lt;/choice>
 *       &lt;attribute name="ref" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "constraintTypeOrWordLexiconOrSuggestionOption"
})
@XmlRootElement(name = "default-suggestion-source")
public class DefaultSuggestionSource {

    @XmlElementRefs({
        @XmlElementRef(name = "constraint-type", namespace = "http://marklogic.com/appservices/search", type = JAXBElement.class),
        @XmlElementRef(name = "word-lexicon", namespace = "http://marklogic.com/appservices/search", type = WordLexicon.class),
        @XmlElementRef(name = "annotation", namespace = "http://marklogic.com/appservices/search", type = Annotation.class),
        @XmlElementRef(name = "suggestion-option", namespace = "http://marklogic.com/appservices/search", type = JAXBElement.class)
    })
    protected List<Object> constraintTypeOrWordLexiconOrSuggestionOption = new Vector<Object>();
    @XmlAttribute(name = "ref")
    @XmlSchemaType(name = "anySimpleType")
    protected String ref;

    /**
     * Gets the value of the constraintTypeOrWordLexiconOrSuggestionOption property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the constraintTypeOrWordLexiconOrSuggestionOption property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConstraintTypeOrWordLexiconOrSuggestionOption().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link Annotation }
     * {@link JAXBElement }{@code <}{@link Properties }{@code >}
     * {@link JAXBElement }{@code <}{@link GeoElem }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementQuery }{@code >}
     * {@link JAXBElement }{@code <}{@link Custom }{@code >}
     * {@link JAXBElement }{@code <}{@link GeoElemPair }{@code >}
     * {@link JAXBElement }{@code <}{@link Range }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link WordLexicon }
     * {@link JAXBElement }{@code <}{@link Value }{@code >}
     * {@link JAXBElement }{@code <}{@link Collection }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link GeoAttrPair }{@code >}
     * {@link JAXBElement }{@code <}{@link Word }{@code >}
     * 
     * 
     */
    public List<Object> getConstraintTypeOrWordLexiconOrSuggestionOption() {
        if (constraintTypeOrWordLexiconOrSuggestionOption == null) {
            constraintTypeOrWordLexiconOrSuggestionOption = new Vector<Object>();
        }
        return this.constraintTypeOrWordLexiconOrSuggestionOption;
    }

    public boolean isSetConstraintTypeOrWordLexiconOrSuggestionOption() {
        return ((this.constraintTypeOrWordLexiconOrSuggestionOption!= null)&&(!this.constraintTypeOrWordLexiconOrSuggestionOption.isEmpty()));
    }

    public void unsetConstraintTypeOrWordLexiconOrSuggestionOption() {
        this.constraintTypeOrWordLexiconOrSuggestionOption = null;
    }

    /**
     * Gets the value of the ref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRef() {
        return ref;
    }

    /**
     * Sets the value of the ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRef(String value) {
        this.ref = value;
    }

    public boolean isSetRef() {
        return (this.ref!= null);
    }

}
