//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.20 at 02:46:45 PM PDT 
//


/*
 * Copyright 2012 MarkLogic Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.marklogic.client.config.search.jaxb;

import java.util.List;
import java.util.Vector;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://marklogic.com/appservices/search}quotation"/>
 *         &lt;element ref="{http://marklogic.com/appservices/search}implicit"/>
 *         &lt;element ref="{http://marklogic.com/appservices/search}joiner"/>
 *         &lt;element ref="{http://marklogic.com/appservices/search}starter"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "quotationOrImplicitOrJoiner"
})
@XmlRootElement(name = "grammar")
public class Grammar {

    @XmlElements({
        @XmlElement(name = "quotation", type = String.class),
        @XmlElement(name = "implicit", type = Implicit.class),
        @XmlElement(name = "joiner", type = Joiner.class),
        @XmlElement(name = "starter", type = Starter.class)
    })
    protected List<Object> quotationOrImplicitOrJoiner = new Vector<Object>();

    /**
     * Gets the value of the quotationOrImplicitOrJoiner property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the quotationOrImplicitOrJoiner property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQuotationOrImplicitOrJoiner().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * {@link Implicit }
     * {@link Joiner }
     * {@link Starter }
     * 
     * 
     */
    public List<Object> getQuotationOrImplicitOrJoiner() {
        if (quotationOrImplicitOrJoiner == null) {
            quotationOrImplicitOrJoiner = new Vector<Object>();
        }
        return this.quotationOrImplicitOrJoiner;
    }

    public boolean isSetQuotationOrImplicitOrJoiner() {
        return ((this.quotationOrImplicitOrJoiner!= null)&&(!this.quotationOrImplicitOrJoiner.isEmpty()));
    }

    public void unsetQuotationOrImplicitOrJoiner() {
        this.quotationOrImplicitOrJoiner = null;
    }

}
