//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.20 at 02:46:45 PM PDT 
//


/*
 * Copyright 2012 MarkLogic Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.marklogic.client.config.search.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="n" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="s" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="e" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="w" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="latdivs" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="londivs" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "heatmap")
public class Heatmap {

    @XmlAttribute(name = "n", required = true)
    protected double n;
    @XmlAttribute(name = "s", required = true)
    protected double s;
    @XmlAttribute(name = "e", required = true)
    protected double e;
    @XmlAttribute(name = "w", required = true)
    protected double w;
    @XmlAttribute(name = "latdivs", required = true)
    @XmlSchemaType(name = "unsignedInt")
    protected long latdivs;
    @XmlAttribute(name = "londivs", required = true)
    @XmlSchemaType(name = "unsignedInt")
    protected long londivs;

    /**
     * Gets the value of the n property.
     * 
     */
    public double getN() {
        return n;
    }

    /**
     * Sets the value of the n property.
     * 
     */
    public void setN(double value) {
        this.n = value;
    }

    public boolean isSetN() {
        return true;
    }

    /**
     * Gets the value of the s property.
     * 
     */
    public double getS() {
        return s;
    }

    /**
     * Sets the value of the s property.
     * 
     */
    public void setS(double value) {
        this.s = value;
    }

    public boolean isSetS() {
        return true;
    }

    /**
     * Gets the value of the e property.
     * 
     */
    public double getE() {
        return e;
    }

    /**
     * Sets the value of the e property.
     * 
     */
    public void setE(double value) {
        this.e = value;
    }

    public boolean isSetE() {
        return true;
    }

    /**
     * Gets the value of the w property.
     * 
     */
    public double getW() {
        return w;
    }

    /**
     * Sets the value of the w property.
     * 
     */
    public void setW(double value) {
        this.w = value;
    }

    public boolean isSetW() {
        return true;
    }

    /**
     * Gets the value of the latdivs property.
     * 
     */
    public long getLatdivs() {
        return latdivs;
    }

    /**
     * Sets the value of the latdivs property.
     * 
     */
    public void setLatdivs(long value) {
        this.latdivs = value;
    }

    public boolean isSetLatdivs() {
        return true;
    }

    /**
     * Gets the value of the londivs property.
     * 
     */
    public long getLondivs() {
        return londivs;
    }

    /**
     * Sets the value of the londivs property.
     * 
     */
    public void setLondivs(long value) {
        this.londivs = value;
    }

    public boolean isSetLondivs() {
        return true;
    }

}
