//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.20 at 02:46:45 PM PDT 
//


/*
 * Copyright 2012 MarkLogic Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.marklogic.client.config.search.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://marklogic.com/appservices/search}query-resolution-time" minOccurs="0"/>
 *         &lt;element ref="{http://marklogic.com/appservices/search}facet-resolution-time" minOccurs="0"/>
 *         &lt;element ref="{http://marklogic.com/appservices/search}snippet-resolution-time" minOccurs="0"/>
 *         &lt;element ref="{http://marklogic.com/appservices/search}total-time"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "metrics")
public class Metrics {

    @XmlElement(name = "query-resolution-time")
    protected Duration queryResolutionTime;
    @XmlElement(name = "facet-resolution-time")
    protected Duration facetResolutionTime;
    @XmlElement(name = "snippet-resolution-time")
    protected Duration snippetResolutionTime;
    @XmlElement(name = "total-time", required = true)
    protected Duration totalTime;

    /**
     * Gets the value of the queryResolutionTime property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getQueryResolutionTime() {
        return queryResolutionTime;
    }

    /**
     * Sets the value of the queryResolutionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setQueryResolutionTime(Duration value) {
        this.queryResolutionTime = value;
    }

    public boolean isSetQueryResolutionTime() {
        return (this.queryResolutionTime!= null);
    }

    /**
     * Gets the value of the facetResolutionTime property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getFacetResolutionTime() {
        return facetResolutionTime;
    }

    /**
     * Sets the value of the facetResolutionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setFacetResolutionTime(Duration value) {
        this.facetResolutionTime = value;
    }

    public boolean isSetFacetResolutionTime() {
        return (this.facetResolutionTime!= null);
    }

    /**
     * Gets the value of the snippetResolutionTime property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getSnippetResolutionTime() {
        return snippetResolutionTime;
    }

    /**
     * Sets the value of the snippetResolutionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setSnippetResolutionTime(Duration value) {
        this.snippetResolutionTime = value;
    }

    public boolean isSetSnippetResolutionTime() {
        return (this.snippetResolutionTime!= null);
    }

    /**
     * Gets the value of the totalTime property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getTotalTime() {
        return totalTime;
    }

    /**
     * Sets the value of the totalTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setTotalTime(Duration value) {
        this.totalTime = value;
    }

    public boolean isSetTotalTime() {
        return (this.totalTime!= null);
    }

}
