//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.14 at 10:12:12 AM PDT 
//


package com.marklogic.client.config.search.jaxb;

import java.math.BigInteger;
import java.util.List;
import java.util.Vector;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A <b>Options</b> consists of a list of options
 * 					configurations elements.
 * 				
 * 
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
@XmlType(name = "OptionsType", propOrder = {
    "queryOptions"
})
public class Options {

    @XmlElementRefs({
        @XmlElementRef(name = "fragment-scope", namespace = "http://marklogic.com/appservices/search", type = JAXBElement.class),
        @XmlElementRef(name = "annotation", namespace = "http://marklogic.com/appservices/search", type = Annotation.class),
        @XmlElementRef(name = "constraint", namespace = "http://marklogic.com/appservices/search", type = Constraint.class),
        @XmlElementRef(name = "grammar", namespace = "http://marklogic.com/appservices/search", type = Grammar.class),
        @XmlElementRef(name = "term", namespace = "http://marklogic.com/appservices/search", type = Term.class),
        @XmlElementRef(name = "return-constraints", namespace = "http://marklogic.com/appservices/search", type = JAXBElement.class),
        @XmlElementRef(name = "transform-results", namespace = "http://marklogic.com/appservices/search", type = TransformResults.class),
        @XmlElementRef(name = "forest", namespace = "http://marklogic.com/appservices/search", type = JAXBElement.class),
        @XmlElementRef(name = "return-query", namespace = "http://marklogic.com/appservices/search", type = JAXBElement.class),
        @XmlElementRef(name = "return-facets", namespace = "http://marklogic.com/appservices/search", type = JAXBElement.class),
        @XmlElementRef(name = "sort-order", namespace = "http://marklogic.com/appservices/search", type = SortOrder.class),
        @XmlElementRef(name = "default-suggestion-source", namespace = "http://marklogic.com/appservices/search", type = DefaultSuggestionSource.class),
        @XmlElementRef(name = "return-qtext", namespace = "http://marklogic.com/appservices/search", type = JAXBElement.class),
        @XmlElementRef(name = "quality-weight", namespace = "http://marklogic.com/appservices/search", type = JAXBElement.class),
        @XmlElementRef(name = "operator", namespace = "http://marklogic.com/appservices/search", type = Operator.class),
        @XmlElementRef(name = "page-length", namespace = "http://marklogic.com/appservices/search", type = JAXBElement.class),
        @XmlElementRef(name = "suggestion-source", namespace = "http://marklogic.com/appservices/search", type = SuggestionSource.class),
        @XmlElementRef(name = "return-similar", namespace = "http://marklogic.com/appservices/search", type = JAXBElement.class),
        @XmlElementRef(name = "return-metrics", namespace = "http://marklogic.com/appservices/search", type = JAXBElement.class),
        @XmlElementRef(name = "search-option", namespace = "http://marklogic.com/appservices/search", type = JAXBElement.class),
        @XmlElementRef(name = "debug", namespace = "http://marklogic.com/appservices/search", type = JAXBElement.class),
        @XmlElementRef(name = "searchable-expression", namespace = "http://marklogic.com/appservices/search", type = JAXBElement.class),
        @XmlElementRef(name = "concurrency-level", namespace = "http://marklogic.com/appservices/search", type = JAXBElement.class),
        @XmlElementRef(name = "return-plan", namespace = "http://marklogic.com/appservices/search", type = JAXBElement.class),
        @XmlElementRef(name = "additional-query", namespace = "http://marklogic.com/appservices/search", type = JAXBElement.class),
        @XmlElementRef(name = "return-results", namespace = "http://marklogic.com/appservices/search", type = JAXBElement.class)
    })
    protected List<Object> queryOptions = new Vector<Object>();

    /**
     * Gets the value of the queryOptions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the queryOptions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQueryOptions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Annotation }
     * {@link Constraint }
     * {@link Grammar }
     * {@link Term }
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * {@link TransformResults }
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * {@link SortOrder }
     * {@link DefaultSuggestionSource }
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * {@link JAXBElement }{@code <}{@link Double }{@code >}
     * {@link Operator }
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * {@link SuggestionSource }
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * {@link JAXBElement }{@code <}{@link AnyCtsElement }{@code >}
     * 
     * 
     */
    public List<Object> getQueryOptions() {
        if (queryOptions == null) {
            queryOptions = new Vector<Object>();
        }
        return this.queryOptions;
    }

    public boolean isSetQueryOptions() {
        return ((this.queryOptions!= null)&&(!this.queryOptions.isEmpty()));
    }

    public void unsetQueryOptions() {
        this.queryOptions = null;
    }

}
