//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.14 at 10:12:12 AM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://marklogic.com/appservices/search", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.marklogic.client.config.search.jaxb;
