//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.20 at 02:46:45 PM PDT 
//


package com.marklogic.client.config.search.jaxb;

import java.util.List;
import java.util.Vector;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://marklogic.com/appservices/search}match"/>
 *         &lt;group ref="{http://marklogic.com/appservices/search}any-nonsearch-element"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "matchOrAnyOrAny"
})
@XmlRootElement(name = "snippet")
public class Snippet {

    @XmlElementRef(name = "match", namespace = "http://marklogic.com/appservices/search", type = Match.class)
    @XmlAnyElement
    protected List<Object> matchOrAnyOrAny = new Vector<Object>();

    /**
     * Gets the value of the matchOrAnyOrAny property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the matchOrAnyOrAny property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMatchOrAnyOrAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Match }
     * {@link Element }
     * 
     * 
     */
    public List<Object> getMatchOrAnyOrAny() {
        if (matchOrAnyOrAny == null) {
            matchOrAnyOrAny = new Vector<Object>();
        }
        return this.matchOrAnyOrAny;
    }

    public boolean isSetMatchOrAnyOrAny() {
        return ((this.matchOrAnyOrAny!= null)&&(!this.matchOrAnyOrAny.isEmpty()));
    }

    public void unsetMatchOrAnyOrAny() {
        this.matchOrAnyOrAny = null;
    }

}
