//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.20 at 02:46:45 PM PDT 
//


/*
 * Copyright 2012 MarkLogic Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.marklogic.client.config.search.jaxb;

import java.math.BigInteger;
import java.util.List;
import java.util.Vector;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://marklogic.com/appservices/search}additional-query"/>
 *         &lt;element ref="{http://marklogic.com/appservices/search}annotation"/>
 *         &lt;element ref="{http://marklogic.com/appservices/search}debug"/>
 *         &lt;element ref="{http://marklogic.com/appservices/search}forest"/>
 *         &lt;element ref="{http://marklogic.com/appservices/search}page-length"/>
 *         &lt;element ref="{http://marklogic.com/appservices/search}quality-weight"/>
 *         &lt;element ref="{http://marklogic.com/appservices/search}search-option"/>
 *         &lt;element ref="{http://marklogic.com/appservices/search}searchable-expression"/>
 *         &lt;element ref="{http://marklogic.com/appservices/search}sort-order"/>
 *         &lt;element ref="{http://marklogic.com/appservices/search}transform-results"/>
 *       &lt;/choice>
 *       &lt;attribute name="name" use="required" type="{http://marklogic.com/appservices/search}qtext-token" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "additionalQueryOrAnnotationOrDebug"
})
@XmlRootElement(name = "state")
public class State {

    @XmlElementRefs({
        @XmlElementRef(name = "debug", namespace = "http://marklogic.com/appservices/search", type = JAXBElement.class),
        @XmlElementRef(name = "annotation", namespace = "http://marklogic.com/appservices/search", type = Annotation.class),
        @XmlElementRef(name = "transform-results", namespace = "http://marklogic.com/appservices/search", type = TransformResults.class),
        @XmlElementRef(name = "sort-order", namespace = "http://marklogic.com/appservices/search", type = SortOrder.class),
        @XmlElementRef(name = "page-length", namespace = "http://marklogic.com/appservices/search", type = JAXBElement.class),
        @XmlElementRef(name = "forest", namespace = "http://marklogic.com/appservices/search", type = JAXBElement.class),
        @XmlElementRef(name = "searchable-expression", namespace = "http://marklogic.com/appservices/search", type = JAXBElement.class),
        @XmlElementRef(name = "additional-query", namespace = "http://marklogic.com/appservices/search", type = AdditionalQuery.class),
        @XmlElementRef(name = "search-option", namespace = "http://marklogic.com/appservices/search", type = JAXBElement.class),
        @XmlElementRef(name = "quality-weight", namespace = "http://marklogic.com/appservices/search", type = JAXBElement.class)
    })
    protected List<Object> additionalQueryOrAnnotationOrDebug = new Vector<Object>();
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String name;

    /**
     * Gets the value of the additionalQueryOrAnnotationOrDebug property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalQueryOrAnnotationOrDebug property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalQueryOrAnnotationOrDebug().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QueryAnnotation }
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * {@link TransformResults }
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * {@link SortOrder }
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link AdditionalQuery }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Double }{@code >}
     * 
     * 
     */
    public List<Object> getAdditionalQueryOrAnnotationOrDebug() {
        if (additionalQueryOrAnnotationOrDebug == null) {
            additionalQueryOrAnnotationOrDebug = new Vector<Object>();
        }
        return this.additionalQueryOrAnnotationOrDebug;
    }

    public boolean isSetAdditionalQueryOrAnnotationOrDebug() {
        return ((this.additionalQueryOrAnnotationOrDebug!= null)&&(!this.additionalQueryOrAnnotationOrDebug.isEmpty()));
    }

    public void unsetAdditionalQueryOrAnnotationOrDebug() {
        this.additionalQueryOrAnnotationOrDebug = null;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    public boolean isSetName() {
        return (this.name!= null);
    }

}
