//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.14 at 10:12:12 AM PDT 
//


package com.marklogic.client.config.search.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://marklogic.com/appservices/search}fragment-scope" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="collation" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fragmentScope"
})
@XmlRootElement(name = "word-lexicon")
public class WordLexicon {

    @XmlElement(name = "fragment-scope")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String fragmentScope;
    @XmlAttribute(name = "collation")
    @XmlSchemaType(name = "anyURI")
    protected String collation;

    /**
     * Gets the value of the fragmentScope property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFragmentScope() {
        return fragmentScope;
    }

    /**
     * Sets the value of the fragmentScope property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFragmentScope(String value) {
        this.fragmentScope = value;
    }

    public boolean isSetFragmentScope() {
        return (this.fragmentScope!= null);
    }

    /**
     * Gets the value of the collation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCollation() {
        return collation;
    }

    /**
     * Sets the value of the collation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollation(String value) {
        this.collation = value;
    }

    public boolean isSetCollation() {
        return (this.collation!= null);
    }

}
