//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.18 at 11:38:21 AM PDT 
//


package com.marklogic.client.impl.jaxb.security;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.marklogic.client.impl.jaxb.security package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Capability_QNAME = new QName("http://marklogic.com/xdmp/security", "capability");
    private final static QName _Metadata_QNAME = new QName("http://marklogic.com/xdmp/security", "metadata");
    private final static QName _Collections_QNAME = new QName("http://marklogic.com/xdmp/security", "collections");
    private final static QName _DigestPassword_QNAME = new QName("http://marklogic.com/xdmp/security", "digest-password");
    private final static QName _Role_QNAME = new QName("http://marklogic.com/xdmp/security", "role");
    private final static QName _Permissions_QNAME = new QName("http://marklogic.com/xdmp/security", "permissions");
    private final static QName _Action_QNAME = new QName("http://marklogic.com/xdmp/security", "action");
    private final static QName _RoleId_QNAME = new QName("http://marklogic.com/xdmp/security", "role-id");
    private final static QName _Realm_QNAME = new QName("http://marklogic.com/xdmp/security", "realm");
    private final static QName _PasswordExtra_QNAME = new QName("http://marklogic.com/xdmp/security", "password-extra");
    private final static QName _Description_QNAME = new QName("http://marklogic.com/xdmp/security", "description");
    private final static QName _UserName_QNAME = new QName("http://marklogic.com/xdmp/security", "user-name");
    private final static QName _Password_QNAME = new QName("http://marklogic.com/xdmp/security", "password");
    private final static QName _Version_QNAME = new QName("http://marklogic.com/xdmp/security", "version");
    private final static QName _Namespace_QNAME = new QName("http://marklogic.com/xdmp/security", "namespace");
    private final static QName _Ntlmpassword_QNAME = new QName("http://marklogic.com/xdmp/security", "ntlmpassword");
    private final static QName _Kind_QNAME = new QName("http://marklogic.com/xdmp/security", "kind");
    private final static QName _Collection_QNAME = new QName("http://marklogic.com/xdmp/security", "collection");
    private final static QName _LocalName_QNAME = new QName("http://marklogic.com/xdmp/security", "local-name");
    private final static QName _PrivilegeId_QNAME = new QName("http://marklogic.com/xdmp/security", "privilege-id");
    private final static QName _Amp_QNAME = new QName("http://marklogic.com/xdmp/security", "amp");
    private final static QName _User_QNAME = new QName("http://marklogic.com/xdmp/security", "user");
    private final static QName _PrivilegeName_QNAME = new QName("http://marklogic.com/xdmp/security", "privilege-name");
    private final static QName _CollectionId_QNAME = new QName("http://marklogic.com/xdmp/security", "collection-id");
    private final static QName _Compartment_QNAME = new QName("http://marklogic.com/xdmp/security", "compartment");
    private final static QName _UserId_QNAME = new QName("http://marklogic.com/xdmp/security", "user-id");
    private final static QName _DocumentUri_QNAME = new QName("http://marklogic.com/xdmp/security", "document-uri");
    private final static QName _Privilege_QNAME = new QName("http://marklogic.com/xdmp/security", "privilege");
    private final static QName _RoleIds_QNAME = new QName("http://marklogic.com/xdmp/security", "role-ids");
    private final static QName _Uri_QNAME = new QName("http://marklogic.com/xdmp/security", "uri");
    private final static QName _Database_QNAME = new QName("http://marklogic.com/xdmp/security", "database");
    private final static QName _Permission_QNAME = new QName("http://marklogic.com/xdmp/security", "permission");
    private final static QName _AmpId_QNAME = new QName("http://marklogic.com/xdmp/security", "amp-id");
    private final static QName _RoleName_QNAME = new QName("http://marklogic.com/xdmp/security", "role-name");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.marklogic.client.impl.jaxb.security
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RoleJAXB }
     * 
     */
    public RoleJAXB createRoleJAXB() {
        return new RoleJAXB();
    }

    /**
     * Create an instance of {@link PrivilegeJAXB }
     * 
     */
    public PrivilegeJAXB createPrivilegeJAXB() {
        return new PrivilegeJAXB();
    }

    /**
     * Create an instance of {@link MetadataJAXB }
     * 
     */
    public MetadataJAXB createMetadataJAXB() {
        return new MetadataJAXB();
    }

    /**
     * Create an instance of {@link CollectionsJAXB }
     * 
     */
    public CollectionsJAXB createCollectionsJAXB() {
        return new CollectionsJAXB();
    }

    /**
     * Create an instance of {@link RoleIdsJAXB }
     * 
     */
    public RoleIdsJAXB createRoleIdsJAXB() {
        return new RoleIdsJAXB();
    }

    /**
     * Create an instance of {@link PermissionJAXB }
     * 
     */
    public PermissionJAXB createPermissionJAXB() {
        return new PermissionJAXB();
    }

    /**
     * Create an instance of {@link CollectionJAXB }
     * 
     */
    public CollectionJAXB createCollectionJAXB() {
        return new CollectionJAXB();
    }

    /**
     * Create an instance of {@link PasswordExtraJAXB }
     * 
     */
    public PasswordExtraJAXB createPasswordExtraJAXB() {
        return new PasswordExtraJAXB();
    }

    /**
     * Create an instance of {@link UserJAXB }
     * 
     */
    public UserJAXB createUserJAXB() {
        return new UserJAXB();
    }

    /**
     * Create an instance of {@link AmpJAXB }
     * 
     */
    public AmpJAXB createAmpJAXB() {
        return new AmpJAXB();
    }

    /**
     * Create an instance of {@link PermissionsJAXB }
     * 
     */
    public PermissionsJAXB createPermissionsJAXB() {
        return new PermissionsJAXB();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CapabilityJAXB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "capability")
    public JAXBElement<CapabilityJAXB> createCapability(CapabilityJAXB value) {
        return new JAXBElement<CapabilityJAXB>(_Capability_QNAME, CapabilityJAXB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MetadataJAXB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "metadata")
    public JAXBElement<MetadataJAXB> createMetadata(MetadataJAXB value) {
        return new JAXBElement<MetadataJAXB>(_Metadata_QNAME, MetadataJAXB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CollectionsJAXB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "collections")
    public JAXBElement<CollectionsJAXB> createCollections(CollectionsJAXB value) {
        return new JAXBElement<CollectionsJAXB>(_Collections_QNAME, CollectionsJAXB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "digest-password")
    public JAXBElement<String> createDigestPassword(String value) {
        return new JAXBElement<String>(_DigestPassword_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RoleJAXB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "role")
    public JAXBElement<RoleJAXB> createRole(RoleJAXB value) {
        return new JAXBElement<RoleJAXB>(_Role_QNAME, RoleJAXB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PermissionsJAXB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "permissions")
    public JAXBElement<PermissionsJAXB> createPermissions(PermissionsJAXB value) {
        return new JAXBElement<PermissionsJAXB>(_Permissions_QNAME, PermissionsJAXB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "action")
    public JAXBElement<String> createAction(String value) {
        return new JAXBElement<String>(_Action_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "role-id")
    public JAXBElement<BigInteger> createRoleId(BigInteger value) {
        return new JAXBElement<BigInteger>(_RoleId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "realm")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createRealm(String value) {
        return new JAXBElement<String>(_Realm_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PasswordExtraJAXB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "password-extra")
    public JAXBElement<PasswordExtraJAXB> createPasswordExtra(PasswordExtraJAXB value) {
        return new JAXBElement<PasswordExtraJAXB>(_PasswordExtra_QNAME, PasswordExtraJAXB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "user-name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createUserName(String value) {
        return new JAXBElement<String>(_UserName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "password")
    public JAXBElement<String> createPassword(String value) {
        return new JAXBElement<String>(_Password_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "version")
    public JAXBElement<Double> createVersion(Double value) {
        return new JAXBElement<Double>(_Version_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "namespace")
    public JAXBElement<String> createNamespace(String value) {
        return new JAXBElement<String>(_Namespace_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "ntlmpassword")
    public JAXBElement<String> createNtlmpassword(String value) {
        return new JAXBElement<String>(_Ntlmpassword_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KindJAXB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "kind")
    public JAXBElement<KindJAXB> createKind(KindJAXB value) {
        return new JAXBElement<KindJAXB>(_Kind_QNAME, KindJAXB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CollectionJAXB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "collection")
    public JAXBElement<CollectionJAXB> createCollection(CollectionJAXB value) {
        return new JAXBElement<CollectionJAXB>(_Collection_QNAME, CollectionJAXB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "local-name")
    public JAXBElement<String> createLocalName(String value) {
        return new JAXBElement<String>(_LocalName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "privilege-id")
    public JAXBElement<BigInteger> createPrivilegeId(BigInteger value) {
        return new JAXBElement<BigInteger>(_PrivilegeId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AmpJAXB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "amp")
    public JAXBElement<AmpJAXB> createAmp(AmpJAXB value) {
        return new JAXBElement<AmpJAXB>(_Amp_QNAME, AmpJAXB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserJAXB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "user")
    public JAXBElement<UserJAXB> createUser(UserJAXB value) {
        return new JAXBElement<UserJAXB>(_User_QNAME, UserJAXB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "privilege-name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPrivilegeName(String value) {
        return new JAXBElement<String>(_PrivilegeName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "collection-id")
    public JAXBElement<BigInteger> createCollectionId(BigInteger value) {
        return new JAXBElement<BigInteger>(_CollectionId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "compartment")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCompartment(String value) {
        return new JAXBElement<String>(_Compartment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "user-id")
    public JAXBElement<BigInteger> createUserId(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "document-uri")
    public JAXBElement<String> createDocumentUri(String value) {
        return new JAXBElement<String>(_DocumentUri_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrivilegeJAXB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "privilege")
    public JAXBElement<PrivilegeJAXB> createPrivilege(PrivilegeJAXB value) {
        return new JAXBElement<PrivilegeJAXB>(_Privilege_QNAME, PrivilegeJAXB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RoleIdsJAXB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "role-ids")
    public JAXBElement<RoleIdsJAXB> createRoleIds(RoleIdsJAXB value) {
        return new JAXBElement<RoleIdsJAXB>(_RoleIds_QNAME, RoleIdsJAXB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "uri")
    public JAXBElement<String> createUri(String value) {
        return new JAXBElement<String>(_Uri_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "database")
    public JAXBElement<BigInteger> createDatabase(BigInteger value) {
        return new JAXBElement<BigInteger>(_Database_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PermissionJAXB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "permission")
    public JAXBElement<PermissionJAXB> createPermission(PermissionJAXB value) {
        return new JAXBElement<PermissionJAXB>(_Permission_QNAME, PermissionJAXB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "amp-id")
    public JAXBElement<BigInteger> createAmpId(BigInteger value) {
        return new JAXBElement<BigInteger>(_AmpId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/security", name = "role-name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createRoleName(String value) {
        return new JAXBElement<String>(_RoleName_QNAME, String.class, null, value);
    }

}
