//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.18 at 11:38:21 AM PDT 
//


package com.marklogic.client.impl.jaxb.security;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 * 	A privilege on a function/built-in.
 *       
 * 
 * <p>Java class for privilege complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="privilege">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://marklogic.com/xdmp/security}privilege-id"/>
 *         &lt;element ref="{http://marklogic.com/xdmp/security}privilege-name"/>
 *         &lt;element ref="{http://marklogic.com/xdmp/security}action"/>
 *         &lt;element ref="{http://marklogic.com/xdmp/security}kind"/>
 *         &lt;element ref="{http://marklogic.com/xdmp/security}role-ids"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "privilege", propOrder = {

})
public class PrivilegeJAXB {

    @XmlElement(name = "privilege-id", required = true)
    protected BigInteger privilegeId;
    @XmlElement(name = "privilege-name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String privilegeName;
    @XmlElement(required = true)
    protected String action;
    @XmlElement(required = true)
    protected KindJAXB kind;
    @XmlElement(name = "role-ids", required = true)
    protected RoleIdsJAXB roleIds;

    /**
     * Gets the value of the privilegeId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrivilegeId() {
        return privilegeId;
    }

    /**
     * Sets the value of the privilegeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrivilegeId(BigInteger value) {
        this.privilegeId = value;
    }

    /**
     * Gets the value of the privilegeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivilegeName() {
        return privilegeName;
    }

    /**
     * Sets the value of the privilegeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivilegeName(String value) {
        this.privilegeName = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the kind property.
     * 
     * @return
     *     possible object is
     *     {@link KindJAXB }
     *     
     */
    public KindJAXB getKind() {
        return kind;
    }

    /**
     * Sets the value of the kind property.
     * 
     * @param value
     *     allowed object is
     *     {@link KindJAXB }
     *     
     */
    public void setKind(KindJAXB value) {
        this.kind = value;
    }

    /**
     * Gets the value of the roleIds property.
     * 
     * @return
     *     possible object is
     *     {@link RoleIdsJAXB }
     *     
     */
    public RoleIdsJAXB getRoleIds() {
        return roleIds;
    }

    /**
     * Sets the value of the roleIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleIdsJAXB }
     *     
     */
    public void setRoleIds(RoleIdsJAXB value) {
        this.roleIds = value;
    }

}
