//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.18 at 11:38:21 AM PDT 
//


package com.marklogic.client.impl.jaxb.security;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 *         The user object
 *       
 * 
 * <p>Java class for user complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="user">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://marklogic.com/xdmp/security}user-id"/>
 *         &lt;element ref="{http://marklogic.com/xdmp/security}user-name"/>
 *         &lt;element ref="{http://marklogic.com/xdmp/security}description"/>
 *         &lt;element ref="{http://marklogic.com/xdmp/security}password"/>
 *         &lt;element ref="{http://marklogic.com/xdmp/security}digest-password"/>
 *         &lt;element ref="{http://marklogic.com/xdmp/security}password-extra" minOccurs="0"/>
 *         &lt;element ref="{http://marklogic.com/xdmp/security}role-ids"/>
 *         &lt;element ref="{http://marklogic.com/xdmp/security}permissions"/>
 *         &lt;element ref="{http://marklogic.com/xdmp/security}collections"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "user", propOrder = {

})
public class UserJAXB {

    @XmlElement(name = "user-id", required = true)
    protected BigInteger userId;
    @XmlElement(name = "user-name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String userName;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String password;
    @XmlElement(name = "digest-password", required = true)
    protected String digestPassword;
    @XmlElement(name = "password-extra")
    protected PasswordExtraJAXB passwordExtra;
    @XmlElement(name = "role-ids", required = true)
    protected RoleIdsJAXB roleIds;
    @XmlElement(required = true)
    protected PermissionsJAXB permissions;
    @XmlElement(required = true)
    protected CollectionsJAXB collections;

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUserId(BigInteger value) {
        this.userId = value;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the digestPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDigestPassword() {
        return digestPassword;
    }

    /**
     * Sets the value of the digestPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDigestPassword(String value) {
        this.digestPassword = value;
    }

    /**
     * Gets the value of the passwordExtra property.
     * 
     * @return
     *     possible object is
     *     {@link PasswordExtraJAXB }
     *     
     */
    public PasswordExtraJAXB getPasswordExtra() {
        return passwordExtra;
    }

    /**
     * Sets the value of the passwordExtra property.
     * 
     * @param value
     *     allowed object is
     *     {@link PasswordExtraJAXB }
     *     
     */
    public void setPasswordExtra(PasswordExtraJAXB value) {
        this.passwordExtra = value;
    }

    /**
     * Gets the value of the roleIds property.
     * 
     * @return
     *     possible object is
     *     {@link RoleIdsJAXB }
     *     
     */
    public RoleIdsJAXB getRoleIds() {
        return roleIds;
    }

    /**
     * Sets the value of the roleIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleIdsJAXB }
     *     
     */
    public void setRoleIds(RoleIdsJAXB value) {
        this.roleIds = value;
    }

    /**
     * Gets the value of the permissions property.
     * 
     * @return
     *     possible object is
     *     {@link PermissionsJAXB }
     *     
     */
    public PermissionsJAXB getPermissions() {
        return permissions;
    }

    /**
     * Sets the value of the permissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link PermissionsJAXB }
     *     
     */
    public void setPermissions(PermissionsJAXB value) {
        this.permissions = value;
    }

    /**
     * Gets the value of the collections property.
     * 
     * @return
     *     possible object is
     *     {@link CollectionsJAXB }
     *     
     */
    public CollectionsJAXB getCollections() {
        return collections;
    }

    /**
     * Sets the value of the collections property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollectionsJAXB }
     *     
     */
    public void setCollections(CollectionsJAXB value) {
        this.collections = value;
    }

}
