prefix foaf: <http://xmlns.com/foaf/0.1/>

select distinct ?name1 ?name2
WHERE
{
  ?p1 foaf:knows ?p2 ;
      foaf:name ?name1 .
  ?p2 foaf:schoolHomepage <http://www.swarthmore.edu/> ;
      foaf:name ?name2
}
