//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.18 at 11:38:21 AM PDT 
//


package com.marklogic.client.impl.jaxb.metadata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for metadata complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="metadata">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://marklogic.com/rest-api}collections" minOccurs="0"/>
 *         &lt;element ref="{http://marklogic.com/rest-api}permissions" minOccurs="0"/>
 *         &lt;element ref="{http://marklogic.com/xdmp/property}properties" minOccurs="0"/>
 *         &lt;element ref="{http://marklogic.com/rest-api}quality" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="uri" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "metadata")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "metadata", propOrder = {
    "collections",
    "permissions",
    "properties",
    "quality"
})
public class MetadataJAXB {

    protected CollectionsJAXB collections;
    protected PermissionsJAXB permissions;
    @XmlElement(namespace = "http://marklogic.com/xdmp/property")
    protected PropertiesJAXB properties;
    @XmlElement(type = Integer.class)
    protected int quality;
    @XmlAttribute
    protected String uri;

    /**
     * Gets the value of the collections property.
     * 
     * @return
     *     possible object is
     *     {@link CollectionsJAXB }
     *     
     */
    public CollectionsJAXB getCollections() {
        return collections;
    }

    /**
     * Sets the value of the collections property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollectionsJAXB }
     *     
     */
    public void setCollections(CollectionsJAXB value) {
        this.collections = value;
    }

    /**
     * Gets the value of the permissions property.
     * 
     * @return
     *     possible object is
     *     {@link PermissionsJAXB }
     *     
     */
    public PermissionsJAXB getPermissions() {
        return permissions;
    }

    /**
     * Sets the value of the permissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link PermissionsJAXB }
     *     
     */
    public void setPermissions(PermissionsJAXB value) {
        this.permissions = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link PropertiesJAXB }
     *     
     */
    public PropertiesJAXB getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesJAXB }
     *     
     */
    public void setProperties(PropertiesJAXB value) {
        this.properties = value;
    }

    /**
     * Gets the value of the quality property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getQuality() {
        return quality;
    }

    /**
     * Sets the value of the quality property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setQuality(int value) {
        this.quality = value;
    }

    /**
     * Gets the value of the uri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUri() {
        return uri;
    }

    /**
     * Sets the value of the uri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUri(String value) {
        this.uri = value;
    }

}
