//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.18 at 11:38:21 AM PDT 
//


package com.marklogic.client.impl.jaxb.metadata;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import com.marklogic.client.impl.jaxb.security.CapabilityJAXB;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.marklogic.client.impl.jaxb.metadata package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Permission_QNAME = new QName("http://marklogic.com/rest-api", "permission");
    private final static QName _RoleName_QNAME = new QName("http://marklogic.com/rest-api", "role-name");
    private final static QName _Quality_QNAME = new QName("http://marklogic.com/rest-api", "quality");
    private final static QName _Collection_QNAME = new QName("http://marklogic.com/rest-api", "collection");
    private final static QName _Directory_QNAME = new QName("http://marklogic.com/xdmp/property", "directory");
    private final static QName _Properties_QNAME = new QName("http://marklogic.com/xdmp/property", "properties");
    private final static QName _Permissions_QNAME = new QName("http://marklogic.com/rest-api", "permissions");
    private final static QName _Capability_QNAME = new QName("http://marklogic.com/rest-api", "capability");
    private final static QName _Metadata_QNAME = new QName("http://marklogic.com/rest-api", "metadata");
    private final static QName _Collections_QNAME = new QName("http://marklogic.com/rest-api", "collections");
    private final static QName _LastModified_QNAME = new QName("http://marklogic.com/xdmp/property", "last-modified");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.marklogic.client.impl.jaxb.metadata
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PermissionJAXB }
     * 
     */
    public PermissionJAXB createPermissionJAXB() {
        return new PermissionJAXB();
    }

    /**
     * Create an instance of {@link PropertiesJAXB }
     * 
     */
    public PropertiesJAXB createPropertiesJAXB() {
        return new PropertiesJAXB();
    }

    /**
     * Create an instance of {@link MetadataJAXB }
     * 
     */
    public MetadataJAXB createMetadataJAXB() {
        return new MetadataJAXB();
    }

    /**
     * Create an instance of {@link CollectionsJAXB }
     * 
     */
    public CollectionsJAXB createCollectionsJAXB() {
        return new CollectionsJAXB();
    }

    /**
     * Create an instance of {@link PermissionsJAXB }
     * 
     */
    public PermissionsJAXB createPermissionsJAXB() {
        return new PermissionsJAXB();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PermissionJAXB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/rest-api", name = "permission")
    public JAXBElement<PermissionJAXB> createPermission(PermissionJAXB value) {
        return new JAXBElement<PermissionJAXB>(_Permission_QNAME, PermissionJAXB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/rest-api", name = "role-name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createRoleName(String value) {
        return new JAXBElement<String>(_RoleName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/rest-api", name = "quality")
    public JAXBElement<BigInteger> createQuality(BigInteger value) {
        return new JAXBElement<BigInteger>(_Quality_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/rest-api", name = "collection")
    public JAXBElement<String> createCollection(String value) {
        return new JAXBElement<String>(_Collection_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/property", name = "directory")
    public JAXBElement<String> createDirectory(String value) {
        return new JAXBElement<String>(_Directory_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PropertiesJAXB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/property", name = "properties")
    public JAXBElement<PropertiesJAXB> createProperties(PropertiesJAXB value) {
        return new JAXBElement<PropertiesJAXB>(_Properties_QNAME, PropertiesJAXB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PermissionsJAXB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/rest-api", name = "permissions")
    public JAXBElement<PermissionsJAXB> createPermissions(PermissionsJAXB value) {
        return new JAXBElement<PermissionsJAXB>(_Permissions_QNAME, PermissionsJAXB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CapabilityJAXB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/rest-api", name = "capability")
    public JAXBElement<CapabilityJAXB> createCapability(CapabilityJAXB value) {
        return new JAXBElement<CapabilityJAXB>(_Capability_QNAME, CapabilityJAXB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MetadataJAXB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/rest-api", name = "metadata")
    public JAXBElement<MetadataJAXB> createMetadata(MetadataJAXB value) {
        return new JAXBElement<MetadataJAXB>(_Metadata_QNAME, MetadataJAXB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CollectionsJAXB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/rest-api", name = "collections")
    public JAXBElement<CollectionsJAXB> createCollections(CollectionsJAXB value) {
        return new JAXBElement<CollectionsJAXB>(_Collections_QNAME, CollectionsJAXB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://marklogic.com/xdmp/property", name = "last-modified")
    public JAXBElement<XMLGregorianCalendar> createLastModified(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_LastModified_QNAME, XMLGregorianCalendar.class, null, value);
    }

}
