//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.18 at 11:38:21 AM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://marklogic.com/rest-api", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.marklogic.client.impl.jaxb.metadata;
